### ISSUE TITLE
Game does not work, runs out of ram?

### ISSUE THREAD

**Issue by ziggymann** [yokoboko/TetrisDuino#1]
When starting the game, the tetris block seems to fall but gets stuck, after resetting it just gets stuck

https://github.com/yokoboko/TetrisDuino/assets/152087658/87f019bd-1dba-4098-aa89-c32aec095cd5

**Comment by yokoboko** [comment]
I have no clue what is wrong here. Maybe try to debug and figure out. It is strange that it does that after a button press.

**Comment by ziggymann** [comment]
Could be a ram issue, I don't know, do you have an old version of the code?

**Comment by yokoboko** [comment]
Try this one and let me know:
https://drive.google.com/file/d/1BkaDbJbFBHgQIF0_XEbw5fB_0jec16ea/view?usp=drive_link

**Comment by ziggymann** [comment]
I will try that code, on a side note, if I ever try it with an arduino pro mini, will it work?

**Comment by yokoboko** [comment]
It should work. You should double check if you wired it correctly and the connection is good. Sometimes on the breadboard the wiring might introduce some noise when when you push hard the buttons.

 The issue here is not out of ram. Something is happening after you press a button the whole program/arduino freezes.

**Comment by ziggymann** [comment]
In the video, the freezing happened before any movement button was pressed, shortly after the start button

**Comment by yokoboko** [comment]
Are you sure the wiring is good and there is no noise?

**Comment by ziggymann** [comment]
Yes, checked the wiring a few times

Also, is this the similar amount?
![image](https://github.com/yokoboko/TetrisDuino/assets/152087658/9678f77c-76a3-4d9a-a1fa-b0b93b82f874)

**Comment by yokoboko** [comment]
Seems fine to me.

You should try to debug and figure out why it freezes. The code has been tested by a few other people and it seems to work for them. For now, I don't have reason to believe that something is wrong in the game's code.

**Comment by ziggymann** [comment]
Alright, I'll check the old code when I can and get back to you

**Comment by yokoboko** [comment]
Did you use the diagram for wiring or did you change some of the pins?

**Comment by ziggymann** [comment]
Tried the old code, all of the pins are the same, didn't work

**Comment by yokoboko** [comment]
Sorry to hear that. I currently don't have the needed hardware to test it out. If you figure out what is the issue, please let me know. 
Good luck!

**Comment by ziggymann** [comment]
Ok
